"""Emit the English hyphenation pattern table the leaf vetoes with.

The English leaf hyphenates automatically (`Hyphens.Auto`) but vetoes the
breaks no book keeps (domain/EnglishHyphenation.kt): the breaker cannot be
told that *de-scends* is not a break. The vetoes come from the TeX
US-English patterns — the same table browsers hyphenate with.

    python3 tools/build_hyphen_table.py

Reads the pyphen-bundled hyph_en_US.dic (hunspell format) and writes
app/src/main/java/com/beautifulquran/domain/HyphenTable.kt. The table is
committed: the leaf must veto identically on every machine, with no network
and no native hyphenator. Re-run only to deliberately change the table (and
bump EnglishBookCache.FORMAT — every leaf breaks somewhere new).

License: BSD-style grant ("unlimited copying, redistribution and
modification ... with this copyright and license information"). Provenance:
the plain TeX hyphenation table (Donald Knuth, `hyphen.tex`) via the
OpenOffice `hyph_en_US.dic` conversion by Laszlo Nemeth, as bundled with
pyphen; original licenses `hyphen.tex` (unlimited copying/redistribution;
modifications only under another name) and the TUGboat exception log
(C) 2007 TeX Users Group, free to use, modify and distribute.
"""

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "app/src/main/java/com/beautifulquran/domain/HyphenTable.kt"

HEADER = """\
package com.beautifulquran.domain

/**
 * US-English hyphenation patterns the English leaf vetoes with.
 *
 * Generated by `python3 tools/build_hyphen_table.py` — do not hand-edit.
 * Provenance and license: see the script. Split into parts: one 11k
 * `arrayOf` blows past the JVM's 64 KB method limit.
 */
"""

PART_SIZE = 1400


def load_patterns() -> list[str]:
    try:
        import pyphen
    except ImportError:
        sys.exit("pyphen is required: pip install pyphen")
    dic = Path(pyphen.__file__).parent / "dictionaries" / "hyph_en_US.dic"
    lines = dic.read_text(encoding="utf-8").splitlines()
    patterns = [
        ln.strip()
        for ln in lines
        if ln.strip() and not ln.startswith(("UTF", "LEFT", "RIGHT", "COMPOUND"))
    ]
    assert len(patterns) > 10_000, f"expected ~11k patterns, got {len(patterns)}"
    ref = pyphen.Pyphen(lang="en_US")
    for word, want in {
        "righteousness": "right-eous-ness",
        "transgress": "trans-gress",
        "fulfillment": "ful-fill-ment",
        "guidance": "guid-ance",
        "promise": "prom-ise",
    }.items():
        assert ref.inserted(word) == want, f"reference drift on {word}"
    return patterns


def main() -> None:
    patterns = load_patterns()
    parts = []
    for n in range(0, len(patterns), PART_SIZE):
        body = "".join(f'    "{p}",\n' for p in patterns[n : n + PART_SIZE])
        parts.append(
            f"private fun hyphenPart{len(parts)}(): Array<String> = arrayOf(\n{body})\n"
        )
    combined = " + ".join(f"hyphenPart{n}()" for n in range(len(parts)))
    OUT.write_text(
        HEADER + "\n".join(parts)
        + f"\ninternal val HYPHEN_PATTERNS: Array<String> = {combined}\n",
        encoding="utf-8",
    )
    print(f"wrote {len(patterns)} patterns ({OUT.stat().st_size // 1024} KiB)")


if __name__ == "__main__":
    main()
